language: php
php:
  - "5.5"
  - "5.4"
env:
services: riak
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq protobuf-c protobuf-c-dev valgrind
  - git submodule update --init --recursive
before_script:
  - "ulimit -n 2048"
  - ./script/build_riack.sh 127.0.0.1 8087
  - ./script/build_module.sh
script:
  - ./script/test_riack.sh
  - PHP=`which php`
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$PHP $PHP run-tests.php -q -m --show-diff
