language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
env:
services: riak
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind
  - git submodule update --init --recursive
before_script:
  - "ulimit -n 2048"
  - ./script/build_module.sh
  - search-cmd install testsearch
script:
  - PHP=`which php`
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$PHP $PHP run-tests.php -q -m --show-diff
