language: php
php:
  - "5.5"
  - "5.4"
services:
  - riak
before_script:
  - "ulimit -n 2048"
  - ./script/build_module.sh
script:
  - PHP=`which php`
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$PHP $PHP run-tests.php -q
